const ideas = [
    "Picnic in the park with friends",
    "Try a new yoga class",
    "Movie night with homemade popcorn",
    "Explore a nearby hiking trail",
    "Host a game night with friends",
    "Go for a bike ride by the beach",
    "Visit a local museum or gallery",
    "Try a new recipe and cook",
    "Go stargazing in a clear night sky",
    "Take a scenic drive to relax",
    "Plant a small herb garden",
    "Go camping in a nearby forest",
    "Visit a local farmer's market",
    "Create your own DIY home decor",
    "Attend a live music performance",
    "Learn a new musical instrument",
    "Take a photography walk in nature",
    "Read a book in a cozy café",
    "Explore a new neighborhood on foot",
    "Join a local sports club",
    "Have a picnic on the beach",
    "Learn a new dance style",
    "Visit an amusement park or fair",
    "Have a movie marathon at home",
    "Try paddleboarding or kayaking",
    "Visit a nearby botanical garden",
    "Take a scenic train ride",
    "Learn a new language online",
    "Paint or draw in an art class",
    "Take a day trip to a neighboring city",
    "Visit a nearby zoo or animal sanctuary",
    "Try a new water sport",
    "Have a picnic in your backyard",
    "Attend a local food festival",
    "Explore a nearby historical site",
    "Go for a sunrise or sunset hike",
    "Take a cooking class",
    "Have a DIY spa day at home",
    "Visit a local bookstore or library",
    "Try birdwatching in a nature reserve",
    "Take a pottery or ceramics workshop",
    "Attend a comedy show or improv night",
    "Explore a new bike trail",
    "Go for a swim in a natural lake",
    "Have a karaoke night with friends",
    "Visit a nearby beach or seaside town",
    "Try a virtual reality gaming experience",
    "Join a local book club",
    "Take a painting class",
    "Explore a nearby waterfall or scenic spot",
    "Go for a scenic horseback ride",
"Try indoor rock climbing",
"Visit a local escape room",
"Attend a wine tasting event",
"Take a pottery painting workshop",
"Go for a leisurely bike ride",
"Have a DIY picnic in your backyard",
"Join a local photography club",
"Try a new board game with friends",
"Take a scenic boat tour",
"Visit a nearby art exhibition",
"Go for a relaxing spa massage",
"Try a virtual fitness class",
"Attend a stand-up comedy show",
"Take a nature photography workshop",
"Go for a swim in a natural river",
"Host a DIY craft night with friends",
"Visit a local historic house or castle",
"Try indoor trampoline park",
"Have a karaoke night at a local bar",
"Take a scenic helicopter tour",
"Join a local hiking or walking group",
"Try a pottery wheel throwing class",
"Visit a nearby aquarium or marine park",
"Go for a leisurely walk in a botanical park",
"Have a picnic at a scenic lookout point",
"Try a virtual painting and wine session",
"Take a scenic road trip to a new town",
"Attend a local theater production",
"Go for a paddleboat ride on a lake",
"Host a themed costume party at home",
"Visit a local planetarium or observatory",
"Try a new fitness activity, like kickboxing",
"Take a scenic hot air balloon ride",
"Go for a leisurely golfing session",
"Try a virtual reality escape room",
"Host a movie night under the stars",
"Visit a local wildlife sanctuary",
"Take a cooking class focused on international cuisine",
"Go for a scenic horse-drawn carriage ride",
"Try indoor ice skating or rollerblading",
"Have a DIY wine and cheese tasting",
"Visit a nearby farm or petting zoo",
"Go for a relaxing paddleboard yoga session",
"Host a DIY home spa party with friends",
"Try a virtual cooking class",
"Take a scenic river cruise",
"Go for a leisurely fishing trip",
"Try a pottery hand-building workshop",
"Visit a local arboretum or botanical garden",
"Have a DIY game night with homemade games",
"Go for a scenic horseback trail ride",
"Try a virtual reality arcade",
"Attend a live outdoor concert",
"Take a photography tour in the city",
"Go for a leisurely paddleboarding session",
"Host a DIY outdoor movie night",
"Visit a local sculpture park or garden",
"Try a new water activity like jet skiing",
"Take a scenic helicopter sightseeing tour",
"Go for a relaxing yoga retreat",
"Try indoor go-kart racing",
"Have a DIY wine tasting with friends",
"Visit a nearby botanical greenhouse",
"Go for a leisurely picnic by a waterfall",
"Try a virtual dance fitness class",
"Take a guided wildlife safari tour",
"Go for a soothing meditation session",
"Host a DIY backyard camping adventure",
"Visit a local historical reenactment",
"Try indoor archery or axe throwing",
"Have a karaoke night with a twist",
"Take a scenic hot air balloon flight",
"Try a virtual escape room experience",
"Join a local birdwatching club",
"Visit a nearby chocolate or candy factory",
"Go for a leisurely horse-drawn carriage ride",
"Host a DIY outdoor painting party",
"Visit a local indoor trampoline park",
"Try a virtual wine and paint night",
"Take a scenic train journey through the countryside",
"Go for a relaxing meditation retreat",
"Try a pottery glazing and firing workshop",
"Visit a nearby butterfly or insect garden",
"Have a picnic in a blooming flower field",
"Try indoor laser tag or paintball",
"Take a scenic boat cruise along the coast",
"Go for a leisurely segway tour",
"Try a virtual reality roller coaster ride",
"Host a DIY backyard barbecue party",
"Visit a local pet cafe or animal shelter",
"Go for a soothing Tai Chi or Qi Gong class",
"Try a pottery sculpting workshop",
"Take a scenic sunset boat tour",
"Go for a leisurely photography walk in the city",
"Host a DIY outdoor treasure hunt",
"Visit a nearby historic lighthouse",
"Try indoor mini golf or bowling",
"Have a DIY homemade ice cream tasting",
"Visit a local bonsai or botanical bonsai garden",
"Go for a relaxing spa day at a wellness retreat",
"Try a virtual reality art creation experience",
"Play a game of tennis",
"Go for a bike ride",
"Have a picnic in the park",
"Try indoor rock climbing",
"Go for a swim at the beach",
"Play a round of golf",
"Take a hike in nature",
"Go fishing in a nearby lake",
"Try paddleboarding on a river",
"Join a recreational sports league",
"Practice meditation for 10 minutes",
"Engage in deep breathing exercises",
"Go for a mindful walk in nature",
"Practice yoga or stretching",
"Try a guided mindfulness meditation",
"Engage in mindful eating, savoring each bite",
"Journal your thoughts and feelings",
"Listen to calming music or nature sounds",
"Create a gratitude list or journal",
"Engage in a mindful coloring activity",
"Practice mindful gardening or tending to plants",
"Take a relaxing bath or shower mindfully",
"Engage in body scan meditation",
"Read a book mindfully, focusing on each word",
"Practice mindful photography, capturing moments of beauty",
"Engage in a mindful listening exercise, paying attention to sounds around you",

]

export default ideas